#! /usr/bin/env python
# lc - letter count (similar to POSIX standard tool wc - word count)
# counts unique letters from stdin or a text file and
# outputs a list of the letters
#

import sys, codecs, os.path

if len(sys.argv) != 2:
  data = unicode(sys.stdin.read(), 'utf-8')

  if len(data) == 0:
    print 'Usage: lc <String or Filename>'
    exit(1)
else:
  if os.path.isfile(sys.argv[1]):
    f = codecs.open(sys.argv[1], 'r', 'utf-8')
    data = f.read()
    f.close()
  else:
    data = unicode(sys.argv[1], 'utf-8')

data = data.replace('\n', ' ')

seen = {}
list = []
for l in data:
  if l in seen: continue
  seen[l] = 1
  list.append(l)

liststr = u''
for elem in list:
  liststr += elem

print u'Input string contains %d unique characters: \n\n%s ' % (len(list), liststr)
