#! /usr/bin/env python
# wikilink returns a wikipedia link to the given keyword
# if it is able to find a corresponding page

# the used wikipedia language can be customized by
# setting WIKI_LANG which defaults to English (en).

import urllib, urllib2;
import sys, os;

if len(sys.argv) < 2:
  print "Usage: wikilang keyword"
  exit;
else:
  keywords = '|'.join(sys.argv[1:])
  keywords = urllib.quote(keywords)

lang = os.getenv('WIKI_LANG', 'en')

url = "http://%s.wikipedia.org/w/api.php?redirect=1&action=query&titles=%s&format=jsonfm" % (lang, keywords)
req = urllib2.Request(url, '', {'User-Agent':'wikilink/1.0'})

res = urllib2.urlopen(req)
print res.read()
